Movies in cinema
levanl/Movie-Tracker-SwiftUI pull request #1
Opened 2024-01-06 19:06 UTC by anachikhladze

Movies in cinema + Movies in cinema details

2024-01-06 19:36 UTC, levanl requested changes

2024-01-06 19:36 UTC, levanl commented on Movie-Tracker-SwiftUI/Movie-Tracker-SwiftUI/Scenes/Movies in Cinema/MoviesInCinemaViewModel.swift
> +        let urlString = "https://api.themoviedb.org/3/movie/now_playing?language=en-US&page=1&api_key=a7105b611883e6587847c2feebcbf151"
უმჯობესია ეს სადმე კონსტანტაში გაიტანო ხოლმე და მერე აქ იქიდან აიღო მაგალითად
struct Constnats {
static API_KEY = "a7105b611883e6587847c2feebcbf151"
static moviesInCinemaEndpoint = ''https://api.themoviedb.org/3/movie/now_playing?language=en-US&page=1&api_key=\(API_KEY)'
}
რაღაც ასე და მერე (https://api.themoviedb.org/3/movie/now_playing?language=en-US&page=1&api_key=a7105b611883e6587847c2feebcbf151) და გაჰარდკოდებული აღარ გექნება

2024-01-06 23:06 UTC, slapiashvili commented on Movie-Tracker-SwiftUI/Movie-Tracker-SwiftUI/Scenes/Movies in Cinema/MoviesInCinemaViewModel.swift
>  import Foundation
არ გინდა Foundation

2024-01-06 23:10 UTC, slapiashvili requested changes
.

2024-01-07 12:35 UTC, anachikhladze commented on Movie-Tracker-SwiftUI/Movie-Tracker-SwiftUI/Scenes/Movies in Cinema/MoviesInCinemaViewModel.swift
> +        let urlString = "https://api.themoviedb.org/3/movie/now_playing?language=en-US&page=1&api_key=a7105b611883e6587847c2feebcbf151"
✅

2024-01-07 12:35 UTC, anachikhladze commented on Movie-Tracker-SwiftUI/Movie-Tracker-SwiftUI/Scenes/Movies in Cinema/MoviesInCinemaViewModel.swift
>  import Foundation
✅

2024-01-07 12:36 UTC, levanl approved these changes

2024-01-07 12:36 UTC, slapiashvili approved these changes
ყველაფერი რიგზეა

2024-01-07 12:37 UTC, MariamKipiani approved these changes

2024-01-07 12:38 UTC, merged